{
  "openapi": "3.0.3",
  "info": {
    "title": "Swagger Peerly-shailendra",
    "description": "Peer to peer appreciations",
    "version": "1.0.11"
  },
  "servers": [
    {
      "url": "http://localhost:33001/"
    }
  ],
  "tags": [
    {
      "name": "Peerly",
      "description": "Peer to peer appreciaiton system"
    }
  ],
  "paths": {
    "/core_values/{coreValueId}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Core Values"],
        "summary": "Update an existing core value",
        "description": "Update an existing core value by Id",
        "operationId": "updateCoreValue",
        "parameters": [
          {
            "name": "coreValueId",
            "in": "path",
            "description": "ID of corevalue",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 32
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Update an existing core value in the organisation",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCoreValues"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateCoreValuesResp"
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid core value id",
                    "value": {
                      "success": false,
                      "message": "Invalid core value id",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "Choose unique core value name",
                    "value": {
                      "success": false,
                      "message": "Choose a unique core value name",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Core Values"],
        "summary": "Finds corevalue by id",
        "description": "get a corevalue corevalue id",
        "operationId": "get a corevalue by id",
        "parameters": [
          {
            "name": "coreValueId",
            "in": "path",
            "description": "ID of corevalue",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 1
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GetCoreValuesResp"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid core value id",
                    "value": {
                      "success": false,
                      "message": "Invalid core value id",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/core_values": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Core Values"],
        "summary": "Add a new core value",
        "description": "Add a new core value",
        "operationId": "addCoreValue",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Create a new core value",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCoreValues"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successfully created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateCoreValuesResp"
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid name",
                    "value": {
                      "success": false,
                      "message": "text field cannot be blank",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "Invalid name",
                    "value": {
                      "success": false,
                      "message": "choose a unique coreValue name",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-3": {
                    "summary": "Invalid description",
                    "value": {
                      "success": false,
                      "message": "description cannot be blank",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-4": {
                    "summary": "Invalid parent core value",
                    "value": {
                      "success": false,
                      "message": "invalid parent core value",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Core Values"],
        "summary": "List all corevalues of the organisation",
        "description": "List all the core values of the specified organisation",
        "operationId": "listCoreValues",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the media type and version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListCoreValuesResp"
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appreciation/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Appreciation"],
        "summary": "get appreciation by id",
        "description": "Display Appreciation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of appreciation",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 28
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AppreciationSuccessResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid input data",
                    "value": {
                      "success": false,
                      "message": "Invalid input data",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Appreciation not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Appreciation not found",
                    "value": {
                      "success": false,
                      "message": "appreciation not found",
                      "status": 404,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appreciation": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Appreciation"],
        "summary": "Create appreciation",
        "description": "Create Appreciation",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAppreciation"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Create Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateAppreciationResp"
                }
              }
            }
          },
          "400": {
            "description": "Appreciation data is not valid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid Corevalue Id",
                    "value": {
                      "success": false,
                      "message": "invalid corevalue id",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "Invalid Receiver Id",
                    "value": {
                      "success": false,
                      "message": "invalid receiver id",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-3": {
                    "summary": "Blank Description",
                    "value": {
                      "success": false,
                      "message": "Description cannot be blank",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Appreciation not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "User Not Found",
                    "value": {
                      "success": false,
                      "message": "User Not Found",
                      "status": 404,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "Invalid corevalue data",
                    "value": {
                      "success": false,
                      "message": "Invalid corevalue data",
                      "status": 404,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/appreciations": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Appreciation"],
        "summary": "Get appreciation list",
        "description": "Get Appreciation",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AppreciationsSuccessResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/login": {
      "get": {
        "tags": ["Login"],
        "summary": "Login",
        "description": "Login to peerly",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "Intranet-Auth",
            "required": true,
            "description": "Intranet Auth token",
            "schema": {
              "enum": [
                "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5Mjl9.6zCALizV0v58UmaJIZ16i1ASULyks6uCj8ubcRrH3dU"
              ],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginSuccessResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/all": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Get user list"],
        "summary": "Get user list",
        "description": "Get user list",
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "description": "name filter",
            "schema": {
              "type": "string"
            },
            "example": "Aditya Ya"
          },
          {
            "name": "page",
            "in": "query",
            "description": "page number",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 1
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "page size",
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "example": 10
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User list fetched",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserListSuccessResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/users/top10": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Get top 10 user list"],
        "summary": "Get top 10 user list",
        "description": "Get top 10 user list",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Top 10 user list fetched",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Top10UserResp"
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/report_appreciation/{id}": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Report Appreciation"],
        "summary": "Report Appreciation",
        "description": "Report Appreciation",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReportAppreciation"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "appreciaiton id",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": 2
          },
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Appreciaiton reported",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReportAppreciationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Report appreciation data is not valid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "You cannot report an appreciation twice",
                    "value": {
                      "success": false,
                      "message": "You cannot report an appreciation twice",
                      "status": 400,
                      "data": null
                    }
                  },
                  "example-2": {
                    "summary": "You cannot report your own appreciation",
                    "value": {
                      "success": false,
                      "message": "You cannot report your own appreciation",
                      "status": 400,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user_profile": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["Get user profile"],
        "summary": "Get user profile",
        "description": "Get user profile",
        "parameters": [
          {
            "in": "header",
            "name": "Accept-Version",
            "required": true,
            "description": "Defines the version of the API endpoint",
            "schema": {
              "enum": ["application/vnd.peerly.v1"],
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User fetched",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserProfileResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unathorized access",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Invalid auth token",
                    "value": {
                      "success": false,
                      "message": "Invalid auth token",
                      "status": 401,
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "example-1": {
                    "summary": "Internal server error",
                    "value": {
                      "success": false,
                      "message": "Internal server error",
                      "status": 500,
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "UpdateCoreValues": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Updated core value"
          },
          "description": {
            "type": "string",
            "example": "updated description"
          }
        }
      },
      "UpdateCoreValuesResp": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "Core value updated"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "parent_id": {
                "type": "integer"
              }
            }
          }
        }
      },
      "CreateCoreValues": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Core value name"
          },
          "description": {
            "type": "string",
            "example": "core value description"
          },
          "parent_core_value_id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          }
        }
      },
      "CreateCoreValuesResp": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "format": "int64"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "parent_core_value_id": {
                "type": "integer",
                "format": "int64"
              }
            }
          }
        }
      },
      "GetCoreValuesResp": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "format": "int64"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "parent_core_value_id": {
                "type": "integer",
                "format": "int64"
              }
            }
          }
        }
      },
      "ListCoreValuesResp": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "parent_core_value_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        }
      },
      "SuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        }
      },
      "Appreciation": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 4
          },
          "core_value_name": {
            "type": "string",
            "example": "Integrity"
          },
          "description": {
            "type": "string",
            "example": "Great teamwork!"
          },
          "is_valid": {
            "type": "boolean",
            "example": true
          },
          "total_rewards": {
            "type": "integer",
            "example": 10
          },
          "quarter": {
            "type": "string",
            "example": 2
          },
          "sender_first_name": {
            "type": "string",
            "example": "John"
          },
          "sender_last_name": {
            "type": "string",
            "example": "Doe"
          },
          "sender_image_url": {
            "type": "string",
            "example": "https://example.com/profile_images/johndoe.jpg"
          },
          "sender_designation": {
            "type": "string",
            "example": "Software Engineer"
          },
          "receiver_first_name": {
            "type": "string",
            "example": "Jane"
          },
          "receiver_last_name": {
            "type": "string",
            "example": "Smith"
          },
          "receiver_image_url": {
            "type": "string",
            "example": "https://example.com/profile_images/janesmith.jpg"
          },
          "receiver_designation": {
            "type": "string",
            "example": "Product Manager"
          },
          "created_at": {
            "type": "integer",
            "example": 1719322966768
          },
          "updated_at": {
            "type": "integer",
            "example": 1719322966768
          }
        }
      },
      "AppreciationsSuccessResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/SuccessResponse"
          },
          {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Appreciation"
                }
              }
            }
          }
        ]
      },
      "AppreciationSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "Appreciation data got successfully"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "$ref": "#/components/schemas/Appreciation"
          }
        }
      },
      "CreateAppreciation": {
        "type": "object",
        "properties": {
          "core_value_id": {
            "type": "integer",
            "example": 1
          },
          "description": {
            "type": "string",
            "example": "Great teamwork"
          },
          "receiver": {
            "type": "integer",
            "example": 5
          }
        }
      },
      "CreateAppreciationResp": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/Appreciation",
            "id": {
              "type": "integer",
              "example": 2
            },
            "core_value_id": {
              "type": "integer",
              "example": 1
            },
            "description": {
              "type": "string",
              "example": "Great teamwork"
            },
            "quarter": {
              "type": "integer",
              "example": 2
            },
            "sender": {
              "type": "integer",
              "example": 6
            },
            "receiver": {
              "type": "integer",
              "example": 5
            },
            "created_at": {
              "type": "integer",
              "example": 1719388759956
            },
            "updated_at": {
              "type": "integer",
              "example": 1719388759956
            }
          }
        }
      },
      "LoginSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "User logged in successfully"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "$ref": "#/components/schemas/LoginResponse"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "User": {
            "$ref": "#/components/schemas/UserData"
          },
          "NewUserCreated": {
            "$ref": "#/components/schemas/NewUserCreated"
          },
          "AuthToken": {
            "$ref": "#/components/schemas/AuthToken"
          }
        }
      },
      "UserData": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 54
          },
          "employee_id": {
            "type": "string",
            "example": "26"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "profile_image_url": {
            "type": "string"
          },
          "role_id": {
            "type": "integer"
          },
          "reward_quota_balance": {
            "type": "integer"
          },
          "designation": {
            "type": "string"
          },
          "grade_id": {
            "type": "integer"
          },
          "grade": {
            "type": "string"
          },
          "created_at": {
            "type": "integer"
          }
        }
      },
      "NewUserCreated": {
        "type": "boolean",
        "example": false
      },
      "AuthToken": {
        "type": "string"
      },
      "GetUserListSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "Intranet Users Listedy"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "$ref": "#/components/schemas/GetUserListData"
          }
        }
      },
      "GetUserListData": {
        "type": "object",
        "properties": {
          "user_list": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "email": {
                  "type": "string"
                },
                "first_name": {
                  "type": "string"
                },
                "last_name": {
                  "type": "string"
                }
              }
            }
          },
          "metadata": {
            "type": "object",
            "properties": {
              "total_count": {
                "type": "integer"
              },
              "current_page": {
                "type": "integer"
              },
              "page_size": {
                "type": "integer"
              }
            }
          }
        }
      },
      "ReportAppreciation": {
        "type": "object",
        "properties": {
          "reporting_comment": {
            "type": "string",
            "example": "false appreciation"
          }
        }
      },
      "ReportAppreciationResponse": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "Intranet Users Listedy"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "appreciation_id": {
                "type": "integer"
              },
              "reporting_comment": {
                "type": "string"
              },
              "reported_by": {
                "type": "integer"
              },
              "reported_at": {
                "type": "integer"
              }
            }
          }
        }
      },
      "Top10UserResp": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "status_code": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                },
                "first_name": {
                  "type": "string"
                },
                "last_name": {
                  "type": "string"
                },
                "profile_image_url": {
                  "type": "string"
                },
                "badge_name": {
                  "type": "string"
                },
                "appreciation_points": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        }
      },
      "GetUserProfileResponse": {
        "type": "object",
        "properties": {
          "success": {
            "example": true
          },
          "message": {
            "example": "User fetched successfully"
          },
          "status_code": {
            "example": 200
          },
          "data": {
            "type": "object",
            "properties": {
              "user_id": {
                "type": "integer",
                "example": 54
              },
              "employee_id": {
                "type": "string",
                "example": "26"
              },
              "first_name": {
                "type": "string"
              },
              "last_name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "profile_image_url": {
                "type": "string"
              },
              "reward_quota_balance": {
                "type": "integer"
              },
              "designation": {
                "type": "string"
              },
              "grade_id": {
                "type": "integer"
              },
              "total_points": {
                "type": "integer"
              },
              "badge": {
                "type": "string"
              },
              "badge_created_at": {
                "type": "integer"
              }
            }
          }
        }
      }
    }
  }
}
